### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by alexw914** [media-sec-lab/Audio-Deepfake-Detection#4]
The results and papers are almost based on ASVspoof2019 challenge. Will you do some survey on some other competions such as ASVspoof2021 and ADD2023?

**Comment by Beyond0814** [comment]
> We will consider an update in the future. Most of the research for ASVspoof2021 builds on ASVspoof2019, while ADD2023 has just been completed.

**Comment by Beyond0814** [comment]
> The results and papers are almost based on ASVspoof2019 challenge. Will you do some survey on some other competions such as ASVspoof2021 and ADD2023?

We will consider an update in the future. Most of the research for ASVspoof2021 builds on ASVspoof2019, while ADD2023 has just been completed.

**Comment by alexw914** [comment]
Thanks
